# Generated by Django 5.1.4 on 2025-01-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
