# Generated by Django 5.1.4 on 2025-01-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0002_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
