# Generated by Django 5.1.4 on 2025-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0003_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
