# Generated by Django 5.1.5 on 2025-01-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0003_barbertime_delete_barberschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barberbooking',
            unique_together=set(),
        ),
    ]
