# Generated by Django 5.1.4 on 2025-01-01 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0004_seat_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=180), '3 минуты'), (datetime.timedelta(seconds=300), '5 минут')]),
        ),
    ]
