# Generated by Django 5.1.4 on 2025-01-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0007_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 минут'), (2, '2 минуты')]),
        ),
    ]
