# Generated by Django 5.1.4 on 2025-01-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0008_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(choices=[(3, '3 часа'), (5, '5 часов')]),
        ),
    ]
