# Generated by Django 5.1.4 on 2025-01-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0009_alter_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
