# Generated by Django 5.1.4 on 2025-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0010_remove_booking_duration_remove_seat_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
