# Generated by Django 5.1.4 on 2025-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0011_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
