# Generated by Django 5.1.5 on 2025-01-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarberBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.barber')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.timeslot')),
            ],
            options={
                'unique_together': {('barber', 'time_slot')},
            },
        ),
    ]
