# Generated by Django 5.1.5 on 2025-02-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0004_alter_barberbooking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.barber')),
            ],
        ),
    ]
